### PR TITLE
Feature/retrieve checkout session

### PR DESCRIPTION
**Pull request by FL33TW00D**
This PR adds the ability to retrieve a checkout session.
Additionally, it adds additional error information.

This PR has been tested on stripe/stripe-mock:v0.134.0

### CODE REVIEW

**Comment by arlyon** [comment]
I have a fix for CI which I will merge today and I'll get this in (downstream crate broke msrv)

**Comment by arlyon** [comment]
If I run:

```sh
> podman run -p12111:12111 -p12112:12112 stripemock/stripe-mock
> http localhost:12111/v1/checkout/sessions 'Authorization: Bearer sk_test_123'
```

I get back this response:

```json
{
    "data": [
        {
            "allow_promotion_codes": null,
            "amount_subtotal": null,
            "amount_total": null,
            "automatic_tax": {
                "enabled": false,
                "status": null
            },
            "billing_address_collection": null,
            "cancel_url": "https://example.com/cancel",
            "client_reference_id": null,
            "currency": null,
            "customer": null,
            "customer_details": null,
            "customer_email": null,
            "id": "cs_test_NaIzywPP28L7DqDVfYkaTZMhBKPH8k6fRwOsX6lqn594a6m8K4nRDiFc",
            "livemode": false,
            "locale": null,
            "metadata": {},
            "mode": "payment",
            "object": "checkout.session",
            "payment_intent": "pi_1IyG7RGVpHUbKwE4EvMa09HS",
            "payment_method_options": {},
            "payment_method_types": [
                "card"
            ],
            "payment_status": "unpaid",
            "setup_intent": null,
            "shipping": null,
            "shipping_address_collection": null,
            "submit_type": null,
            "subscription": null,
            "success_url": "https://example.com/success",
            "total_details": null,
            "url": null
        }
    ],
    "has_more": false,
    "object": "list",
    "url": "/v1/checkout/sessions"
}
```

Is this an issue with stripe-mock?

**Review by arlyon — APPROVED** [review]
LGTM! thanks

**Comment by SorenHolstHansen** [comment]
HI, thanks for fixing this. However I can't figure out how to use this in my project. Do i have to enable a feature flag or something?

**Comment by arlyon** [comment]
Hi! This library hasn't had a release in a while. In the mean time you can directly use master.

**Comment by SorenHolstHansen** [comment]
Thanks

**Pull request merged**
