### PR TITLE
A minimal example using rocket

### PR DESCRIPTION
**Pull request by colin99d**
Adds an example for rocket, since getting parameters and body data is slightly different. This TOML is required to run it:

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"]  }
async-stripe = { version = "0.15", features = ["runtime-tokio-hyper"] }

### CODE REVIEW

**Comment by arlyon** [comment]
Thanks for this! Rocket request limits are interesting as well.

I am waiting for CI and then I'll merge, have a nice Saturday :)

**Comment by colin99d** [comment]
Thanks for the quick review! And sounds good on CI.

**Comment by arlyon** [comment]
Hey! Sorted those issues, please rebase and I'll get this in :)

**Comment by colin99d** [comment]
Got both of those done!

**Pull request merged**
