### PR TITLE
Longer-term fix to removing duplicates

### PR DESCRIPTION
**Pull request by dgramop**
This PR contains a python script that is added to the `openapi-install` Makefile.toml task that finds duplicated structs and enums, and their associated `impl`'s, then merges perfect duplicates together.

It's a basic script and doesn't do the job of the compiler. Since the code generated by openapi is very predictable, my python script can make some assumptions about character placement, ordering of fields, where keywords are, etc. and take a very naive approach to parsing the duplicated code. 

I'm happy to undraft if the duplicate removal is OK as-is for now. The maintainer may weight the urgency of duplicate removal over code quality in the generated/ folder 

The code quality sacrifices for the current state are:
- [x] Limited to just the generated/ folder 
- [x] Results in impl's being reordered and all placed at the bottom of files
- [x] struct, enum, and impl documentation blocks that are placed outside the struct/enum/impl will be misplaced (though this can be fixed with logic I already have implemented that keeps macros in place). Doc comments inside the curly-s will be preserved.
- [x] There may be two crate::resources lines, and the same item may be `use`'d twice

### CODE REVIEW

**Comment by dgramop** [comment]
One more thing, this code doesn't really consider tuple structs. I'm not sure if there are any duplicate tuple structs, but it's worth adding considering that it shouldn't require much modification. For the current state of the repo though, this code should work

**Comment by dgramop** [comment]
It's possible that I'm not building the latest version of the repo right. I tested with an old version of 13 rc3 on crates.io because I could build it through my app. Am I interpreting CONTRIBUTING.md right by using cargo make openapi-install to tell me if the project is building correctly?

**Comment by dgramop** [comment]
> One more thing, this code doesn't really consider tuple structs. I'm not sure if there are any duplicate tuple structs, but it's worth adding considering that it shouldn't require much modification. For the current state of the repo though, this code should work

I did my usual grepping and found no (duplicate) tuple structs are generated. I guess openapi doesn't generate tuple structs, so I won't add those unless openapi changes

**Comment by dgramop** [comment]
@arlyon I finished a script that'll identify and eliminate duplicates automatically. It works and the code it transforms compiles with 

cargo make openapi-install;
cargo build --features runtime-tokio-hyper;

I also adjusted some of the other in generated/resources in order for it to be compatible with the latest version of the stripe API that `cargo make openapi-install` automatically downloaded

**Comment by arlyon** [comment]
This is great. I think the correct approach is to get this code built into the openapi crate so that it never emits duplicated objects, rather than scrubbing them afterwards. Are you able to adjust the script to find out which objects are duplicated and get their paths? Some information on that would go a long way helping us plan how to add this into the codegen.

Thanks for spearheading this feature!

**Comment by dgramop** [comment]
I can definitely adjust the script to just emit what's duplicated and where it's duplicated. My python has been weak; in an effort to strengthen it I decided to write this in python. Forgive me if I'm a little slower to get things back or struggle with python conventions.

**Comment by dgramop** [comment]
Considering that the script just does really simple string comparison (removing some comments and whitespace), for debugging purposes I suggest using a grep situation like this to find duplicates: 
 grep -rh "struct " . | sort | uniq -d
 grep -rh "enum " . | sort | uniq -d

It'll find all the structs (hiding the filenames), and then list duplicates.

I agree that it's probably best to have duplicate removal happen in codegen directly. I'll have to do some careful inspection to understand what's happening behind the scenes before I can be of any help.

Should I close this PR and start looking at doing stuff with the codegen/spec3.json?

**Comment by arlyon** [comment]
I am going to take a look at the other PR now (been away for work), thanks for the work here! :)

**Pull request closed without merging**
