### PR TITLE
fn to expire checkout sessions

### LINKED ISSUE #331: CheckoutSession::expire()
### Is your feature request related to a problem? Please describe.

https://stripe.com/docs/api/checkout/sessions/expire

Stripe allows users to expire checkout sessions. But I don't see an `async-stripe` function to do that.

### Describe the solution you'd like

Add a function that allows doing this
https://stripe.com/docs/api/checkout/sessions/expire

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sloganking**
# Summary

Fixes #331 

### Checklist

- [x] ran `cargo make fmt`
- [x] using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to hightlight user-facing fixes and features

### CODE REVIEW

**Comment by sloganking** [comment]
Looking at CONTRIBUTING.md. I ran 

`cargo test --features runtime-blocking` the 25 unit tests passed. But `tests/account.rs` failed with

```
Running tests/account.rs (target/debug/deps/account-b392d7dfeb7da677)

running 1 test
test is_account_listable ... FAILED

failures:

---- is_account_listable stdout ----
thread 'is_account_listable' panicked at 'error communicating with stripe: error trying to connect: tcp connect error: Connection refused (os error 111)', tests/account.rs:9:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'is_account_listable' panicked at 'assertion failed: result.is_ok()', tests/mock/mod.rs:13:5


failures:
    is_account_listable

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass `--test account`
``` 

I am not sure if I am supposed to put a stripe token somewhere so it will let the test talk to it. 

===

I also ran `cargo +nightly clippy --all --all-targets -- -D warnings`

But it seemed to give back a whole bunch of existing warnings that were not related to my change. So I am not sure if that is actively being followed now.

**Comment by sloganking** [comment]
I'm not sure if taking a mutable reference to a full `CheckoutSession` and replacing the value with the `CheckoutSession` returned from POST, would be better here. As that would entirely prevent mistakenly using the old `CheckoutSession` variable with outdated information. But it is not how the rest of the library functions I have seen here have been doing it.

**Comment by arlyon** [comment]
You raise a cool idea. I am interested in maybe supporting a trait that allows the id but consumes the object. Raise an issue and we can track it! :)

**Review by arlyon — APPROVED** [review]

**Comment by sloganking** [comment]
> Could you prefix your commit message with feat:? We pull those out automatically to generate the change logs.

@arlyon This should be fixed now.

**Comment by arlyon** [comment]
All green, thanks!

**Pull request merged**
