### PR TITLE
CreateTokenCard

### PR DESCRIPTION
**Pull request by o0Ignition0o**
It was part or part [stripe-rs #1](https://github.com/wyyerd/stripe-rs/issues/1), Card token create support.

please let me know if there's anything I can do to improve this :)

### CODE REVIEW

**Comment by arlyon** [comment]
Thanks for the PR! This looks good, but we need to put it in `src/resources/token_ext.rs`, everything in the `generated` folder will be overwritten.

**Comment by o0Ignition0o** [comment]
Oh thanks a lot for your swift feedback!
I'll try to fix it in a couple of hours!

**Comment by o0Ignition0o** [comment]
Ok I think i now understand more how it works,

Just fixed the CONTRIBUTING.md file to advertise the right code generation target name, and I'll try to figure out a way to play with mappings so i can bind the CreateTokenCard type to the generated spec.

Thanks for your feedback! 😊

**Comment by o0Ignition0o** [comment]
After more digging, it seems like this api is deprecated in favor of the payment intents, which are already available here, I m going to close this PR since it's probably not useful anymore. even worse it would actually nudge ppl the wrong way :/

**Pull request closed without merging**
