### PR TITLE
feat: add `Invoice::void`

### PR DESCRIPTION
**Pull request by ferrohd**
# Summary

Adds the `Invoice:void` method closing #517 

### Checklist

- [X] ran `cargo make fmt`
- [X] using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to hightlight user-facing fixes and features

### CODE REVIEW

**Comment by arlyon** [comment]
Running CI, TY

**Comment by ferrohd** [comment]
Merge? @arlyon

**Comment by arlyon** [comment]
TY!

**Pull request merged**
