### PR TITLE
Add "src" as a valid prefix for PaymentMethodId

### PR DESCRIPTION
**Pull request by andrewhalle**

### CODE REVIEW

**Comment by FL33TW00D** [comment]
@andrewhalle can you link the appropriate section of the API docs for this change?

**Comment by andrewhalle** [comment]
@FL33TW00D the [Sources](https://stripe.com/docs/api/sources#sources) API page is listed in the "Payment Methods" section, is there a more specific place I can reference? I noticed this when a PaymentIntent I was testing with failed to de-serialize. Going by the pages listed under "Payment Methods", I suppose I could also add `ba` as a valid prefix for bank accounts, if you agree.

**Comment by FL33TW00D** [comment]
> @FL33TW00D the [Sources](https://stripe.com/docs/api/sources#sources) API page is listed in the "Payment Methods" section, is there a more specific place I can reference? I noticed this when a PaymentIntent I was testing with failed to de-serialize. Going by the pages listed under "Payment Methods", I suppose I could also add `ba` as a valid prefix for bank accounts, if you agree.

Looks good, `ba` and `src` both seem to be valid prefixes. Thanks for the link

**Comment by andrewhalle** [comment]
No problem! I'll add that. Any preference on if I also add a trailing underscore to `pm` and `card`? `PaymentMethodId` seems to be the only `def_id` that doesn't follow that style.

**Comment by arlyon** [comment]
Hey guys thanks for raising this discussion @andrewhalle! I am going to get in touch with people at stripe and get a canonical list of all id formats so that we ensure these are all correct! Stay tuned :)

**Comment by andrewhalle** [comment]
No problem, thank you!

**Pull request merged**
