### PR TITLE
fix: don't pin time-core for msrv

### PR DESCRIPTION
**Pull request by arlyon**
# Summary

Unpin time-core

### CODE REVIEW

**Comment by arlyon** [comment]
Seems like the github is having issues with their CDN, merging anyways

**Comment by timsueberkrueb** [comment]
@arlyon thank you so much! Could we have a crates.io release, please? :pleading_face:

**Comment by arlyon** [comment]
Done, (and closed #418 in the process). Enjoy!

**Comment by arlyon** [comment]
False alarm, seems like crates.io is also timing out (it uses github's CDNs under the hood also). Going to retry a couple of times.

**Comment by timsueberkrueb** [comment]
Hey, @arlyon any news on creating a release? Thanks in advance!

**Pull request merged**
