### PR TITLE
Development option box swap

### PR DESCRIPTION
**Pull request by erichCompSci**
Okay, so I wanted to do these in separate commits, but then I had four commits up and it is maybe easier to view these all at the same time.

1) Login Links Functionality
2) Ephemeral Key Functionality
3) The API Fix
4) The Option and Box Swap

### CODE REVIEW

**Comment by erichCompSci** [comment]
4 pull request, not commits.  Anyway, just check this out when you can and it'll fix your api breakage this weekend when it gets run.

**Comment by arlyon** [comment]
Thanks for this, will merge. Managed to catch covid over the holidays so haven't made any progress on the experiments I was working on. Thanks again for your work on this!

**Comment by imalsogreg** [comment]
@erichCompSci out of curiosity, what was the motivation for `Switched Box and Option around`?

**Comment by erichCompSci** [comment]
@imalsogreg Some of the fields recursively reference each other.  I think I remember APIError being one.  If you remove the Option<Box<>> to Option<> you will see this problem come back and can easily identify them.

The problem with this in Rust is that the compiler then builds an infinitely sized object.  This is a well understood problem and you can find better descriptions in Rust Linked List tutorials.

Why did I change the Box<Option<>> to Option<Box<>>?  Mostly for some ergonomics reasons.  Namely, there are some types (like CreateAccountCapabilities) which don't have defaults or new implementations.  This means you have to write out each inner type.  This is annoying but it's even more annoying when each empty type is a Box::new(None) rather than None.

On top of that matching is also a little weird.  Done Box<Option<>> it looks like:

if let Some(thing) = *var {
}

as opposed to:
if let Some(thing) = var {

}

The second seems to me more natural, but that's a personal preference thing and a little more in line with what I'm seeing in other crates.  Hence the switch.

**Comment by imalsogreg** [comment]
Thanks very much for the explanation :) after bumping our version of async-stripe to HEAD at work I saw I needed to add a ton of `Box`s. If you have to break circular references, yep, makes sense, not much other way around it.

**Pull request merged**
